frontend/engine_1/urls.py
from django.urls import path, include

from . import views

app_name = "engine_1"

urlpatterns = [
	path('', views.home, name="home"),
	path('signup/', views.signup, name="signup"),
	path('login/', views.user_login, name='login'),
	path('logout/', views.user_logout, name='logout'),
	path('<int:id>/upload', views.user_upload, name="user_upload"),
	path('<int:uid>/upload_index/<int:upload_id>', views.user_upload_index, name="user_upload_index"),
	path('<int:id>/profile', views.user_profile, name="user_profile"),
	path('about/', views.about, name="about"),
	path('', include("django.contrib.auth.urls")),
	path('form/', views.index, name="index"),
    path('viz/', views.viz, name="viz"),
    path('scoreboard/', views.scoreboard, name="scoreboard")
]

frontend/frontend/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name='frontend'

urlpatterns = [
	path('engine/', include("engine_1.urls")),
    path('admin/', admin.site.urls),
    # path('engine/', include("engine_1.urls"))
]

frontend/engine_1/models.py
from django.db import models
from django.utils import timezone

import datetime

from django.contrib.auth.models import User

class Uploads(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	filename = models.CharField(max_length=150)
	description = models.CharField(max_length=300, default='')
	date_uploaded = models.DateTimeField('date_published', auto_now_add=True)
	last_opened = models.DateTimeField('last_opened', auto_now=True)
	# last_used = 
	is_valid = models.BooleanField(default=True)

	def __str__(self):
		return f'user: {self.user}, \n \
				filename: {self.filename}, \n \
				description: {self.description} \n \
				date_uploaded: {self.date_uploaded} \n \
				last_opened: {self.last_opened} \n \
				'


class UserProfile(models.Model):

	user = models.OneToOneField(User, on_delete=models.CASCADE)
	# profile_image = models.ImageField(upload_to='profiles')
	uploads = 0

	def __str__(self):
		return f"{user}'s profile"

class CompetitionProfile(models.Model):
	competition_name = models.CharField(max_length=100)
	admin = models.ForeignKey(User, on_delete=models.CASCADE)
	description = models.CharField(max_length=200, default='Welcome!')
	date_created = models.DateTimeField(auto_now_add=True)
	start_datetime = models.DateTimeField(blank=True, null=True)
	end_datetime = models.DateTimeField(blank=True, null=True)

	def __str__(self):
		return f'{self.competition_name} created by {self.admin} on {self.date_created}'

frontend/engine_1/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm
from django.contrib.auth.models import User

from .models import Uploads

class FeedbackForm(forms.Form):
    name = forms.CharField(label='Name')
    email = forms.EmailField(label="Email Address")
    message = forms.CharField(label="Message", widget=forms.Textarea(attrs={'rows': 5}))



class CreateUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = [
			"first_name",
			"last_name",
			"username",
			"email",
			"password1",
			"password2"
		]

	def save(self, commit=True):
		user = super(CreateUserForm, self).save(commit=False)
		user.email = self.cleaned_data.get("email")
		if commit:
			user.save()
		return user

class EditUserForm(UserChangeForm):
	class Meta:
		model = User
		fields = ["first_name", "last_name", "username", "email"]
		exclude = ["password",]


class UploaderForm(ModelForm):
	class Meta:
		model = Uploads
		fields = ["filename", "description"]


	def save(self, commit=True):
		upload = super(UploaderForm, self).save(commit=False)
		# user = User
		
		if commit:
			print(upload)
			upload.save()
		return upload
		# data = {
		# 	'user_id': '',
		# 	'filename': '',
		# 	'description': '',
		# }

frontend/engine_1/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from django.template import loader

from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.urls import reverse

from django.contrib import messages

from .forms import FeedbackForm
from .forms import CreateUserForm
from .forms import UploaderForm
from .forms import EditUserForm

from .models import Uploads

#  ----------------------------------------------------------------------------------------
#  Initial placeholder pages

def index(request):
    # template = loader.get_template('engine_1/index.html')
    if request.method=='POST':
        form=FeedbackForm(request.POST)
        if form.is_valid():
            name=form.cleaned_data['name']
            email=form.cleaned_data['email']
            msg=form.cleaned_data['message']
            # The delay is used to asynchronously process the task
            send_feedback_email_task.delay(name,email,msg)
            return HttpResponseRedirect('viz/')
    else:
        form=FeedbackForm
    # return HttpResponse(template.render({'form':form}, request))
    return render(request,'engine_1/index.html', {'form':form})

def viz(request):
    return HttpResponse("Welcome to Viz!")

#  ----------------------------------------------------------------------------------------

def home(request):
    user = request.user
    # print(user, request.user.is_authenticated)
    if request.user.is_authenticated:
        username = request.user.username
        uploads = Uploads.objects.filter(user=user)
        # print(uploads)
        # uploads = Uploads.objects.select_related('user_id').get(id=user.id)
        context = {'user': user, 'heading': f"Welcome {username}!", 'uploads': uploads}
    else:
        content="Welcome to BenAna, a service used to analyze your script"
        context={'user': None, 'heading': content}
    # return HttpResponse("This is home!")
    return render(request, 'engine_1/home.html', context=context)

def user_login(request):
    if request.user and request.user.is_authenticated:
        return redirect("/engine")
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"{user} logged in.")
                return redirect("/engine")
            else:
                messages.error(request, 'Invalid user login attempt.')
        else:
            messages.error(request, "Invalid username or password")
    form = AuthenticationForm()
    context = {'user': None, 'form': form}
    return render(request=request, template_name="engine_1/login.html", context=context)
    # return HttpResponse("This is the login page")

def user_logout(request):
    user = request.user
    if user and user.is_authenticated:
        logout(request)
        context = {
            'user': user
        }
    else:
        return redirect('/engine')
    return render(request, 'engine_1/logout.html', context=context)

def signup(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            # if form.validate_password
            user = authenticate(username=username, password=raw_password)
            login(user)
            return redirect(reverse('engine_1:home'))
    else:
        form = CreateUserForm()
    return render(request, 'engine_1/signup.html', {'form': form, 'user': None})

def about(request):
    user = request.user if request.user.is_authenticated else None
    context = {
        'user': user,
    }
    return render(request, 'engine_1/about.html', context=context)
    # return HttpResponse("About This App!")

def user_profile(request, id):
    user = request.user if request.user.is_authenticated else None
    if user:
        profile = User.objects.get(pk=user.id)
        if request.method == 'POST':
            form = EditUserForm(request.POST, instance=user)
            # .exclude(field_value="password")
            if form.is_valid():
                form.save()
                return redirect(f'/engine/{user.id}/profile')
        else:
            form = EditUserForm(instance=user)
            context = {
                'form': form
            }
            return render(request, 'engine_1/profile.html', context=context)
    else:
        return redirect(reverse('engine_1:login'))


    # return HttpResponse(f"User {id}'s profile")

def user_upload(request, id):
    user = request.user
    error = None
    if not user.is_authenticated:
        return redirect('/')
    if request.method == 'POST':
        form = UploaderForm(request.POST)
        if form.is_valid():
            upload = form.save(commit=False)
            upload.user = user
            upload.save()
            return redirect(reverse('engine_1:home'))
        error = "Something went wrong :("
    else:
        form = UploaderForm()
    return render(request, 'engine_1/upload.html', {'user': user, 'form': form, 'error': error})

def user_upload_index(request, uid, upload_id):
    user = request.user if request.user.is_authenticated else None
    if user and user.id == uid:
        upload = Uploads.objects.get(pk=upload_id)
        if request.method == 'POST':
            form = UploaderForm(request.POST, instance=upload)
            if form.is_valid():
                upload = form.save(commit=False)
                upload.save()
                return redirect(reverse('engine_1:home'))
        else:
            form = UploaderForm(instance=upload)
            context = {
                'user': user,
                'form': form,
            }
            return render(request, 'engine_1/upload_index.html', context=context)

    return redirect(reverse('engine_1:home'))


def scoreboard(request):
    return render(request, 'engine_1/scoreboard.html', {})

frontend/engine_1/templates/engine_1/about.html
{% extends 'engine_1/base.html' %}

{% block content %}
<div>
	<h1 class="">About BenAna</h1>
	<p>BenAna or Benchmark Analysis is used to analyze your python code!</p>
	<p>It measures and records the runtime and memory used for your script.</p>
	<p>Measurements are tracked and can be viewed.</p>
	
	<div class="mt-3">
		<p>More about the code can be found here!</p>
		<p>Github:</p>
		<p class=""><a href="https://github.com/jyty17/python-fullstack" title="GithubLink">https://github.com/jyty17/python-fullstack</a></p>
	</div>
</div>

{% endblock %}

frontend/engine_1/templates/engine_1/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>BenAna</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body class="container">
	<div class="page-header row justify-content-between navbar navbar-toggler navbar-expand-lg mt-4 mb-4">
		<a href="{% url 'engine_1:home' %}" class=""><h1 class="display-3 text-monospace">BenAna</h1></a>
		<ul class="nav">
			<a href="{% url 'engine_1:home' %}" title="home" class="nav-link">Home</a>
			<a href="{% url 'engine_1:about' %}" title="about" class="nav-link">About</a>
			<a href="{% url 'engine_1:scoreboard' %}" title="scoreboard" class="nav-link">Scoreboard</a>
			{% if user and user.is_authenticated %}
				<a href="{% url 'engine_1:user_upload' user.id %}" title="" class="nav-link">Upload</a>
				<a href="{% url 'engine_1:user_profile' user.id %}" title="" class="nav-link">Profile</a>
			{% else %}
				<a href="{% url 'engine_1:login' %}" title="" class="nav-link">Login</a>
			{% endif %}
		</ul>
	</div>
	<div class="">
		{% block content %}
		{% endblock %}
	</div>
</body>
</html>

frontend/engine_1/templates/engine_1/header.html
{% load static %}
<div>
	<a href="/"><h1>BenAna</h1></a>
	<a href="about/" title="">About</a>
	<a href="upload/" title="">Upload</a>
	<a href="help/" title="">Help</a>
	<a href="profile/" title="">Profile</a>
</div>

frontend/engine_1/templates/engine_1/home.html
{% extends 'engine_1/base.html' %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'engine/home.css' %}">

{% block content %}
<div>
	{% if user %}
		<h1>Engines</h1>

		<p>{{ heading }}</p>
		<div class="card-group">
			{% if uploads %}
				{% for records in uploads %}
					<a href="{% url 'engine_1:user_upload_index' uid=user.id upload_id=records.id %}" class="card card-body">
						<h3 class="card-title">{{ records.filename }}</h3>
						<p class="card-text">{{ records.description }}</p>
					</a>
				{% endfor %}
			{% else %}
				<p>Start uploading -></p>
			{% endif %}
		</div>
	{% else %}
	<div class="mt-5 d-flex justify-content-center flex-column align-items-center">
		<h1 class="display-3">Welcome To BenAna!</h1>
		<p class="display-4">A tool used to analyze your python code!</p>
		<p class="display-4"><a href="{% url 'engine_1:login' %}" title="" class="border border-info p-2 px-5 mt-5 get-started">Get Started!</a></p>
	</div>
	{% endif %}
</div>
{% endblock %}

frontend/engine_1/templates/engine_1/index.html
<!DOCTYPE html>
<html>
<head>
	<title>flex frontend</title>
</head>
<body>
	{% if form %}
		<form method="post" accept-charset="utf-8">
			{{ form }}
			<button type="submit">Submit</button>
		</form>		
	{% endif %}
</body>
</html>

frontend/engine_1/templates/engine_1/login.html
{% extends 'engine_1/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
	<div class="row justify-content-center">
		<div class="col-8">
			<h1>Sign In</h1>
			<form id="login_form" method="post" accept-charset="utf-8" class="form-group">
				{% csrf_token %}
				{{ form|crispy }}
				<input type="submit" value="Login" class="btn btn-success">
				{% if form.errors %}
					<p>Incorrect username or password</p>
				{% endif %}
			</form>
			<div class="row justify-content-between">
				<div>
					<p>Don't have an account?</p>
					<input type="button" onclick="window.location.href='{% url 'engine_1:signup' %}'" value="Sign Up!" class="btn btn-primary">
				</div>
				<input type="button" onclick="" value="Forgot Password" class="btn btn-secondary">
			</div>
		</div>
	</div>
{% endblock %}

frontend/engine_1/templates/engine_1/logout.html
{% extends 'engine_1/base.html' %}

{% block content %}
<div class="d-flex justify-content-center align-content-center mt-5">
	<p class="display-4">You are now logged of user {{ user }} </p>
</div>
{% endblock %}

frontend/engine_1/templates/engine_1/profile.html
{% extends 'engine_1/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div>
	<form action="" method="POST" accept-charset="utf-8" class="form-group">
		{% csrf_token %}
		{{ form|crispy }}
		<input type="submit" name="save" value="Save" class="btn btn-success">
	</form>
	<!-- <a type="submit" name="logout" value="Logout" class="btn btn-danger"> -->
	<a href="{% url 'engine_1:logout' %}" title="logout" class="btn btn-danger">Log Out</a>
	
</div>
{% endblock %}

frontend/engine_1/templates/engine_1/scoreboard.html
{% extends 'engine_1/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div>
	<!-- {{ competition_title }} Scoreboard  -->
	<h1>SCOREBOARD</h1>
</div>
{% endblock %}

frontend/engine_1/templates/engine_1/signup.html
{% extends 'engine_1/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
	<div class="row justify-content-center">
		<div class="col-8">
			<h1>Sign Up</h1>
			<form method="POST" accept-charset="utf-8" class="form-group">
				{% csrf_token %}
				{{ form|crispy }}
				
				<div class="row justify-content-between">
					<input type="submit" value="Create Account" class="btn btn-success">
					<div class="">
						<p>Already have an account?</p>
						<input type="button" onclick="window.location.href='/engine/login'" value="Sign In" class="btn btn-secondary">
					</div>
				</div>
			</form>
		<!-- <p>Already have an account?</p>
		<input type="button" onclick="window.location.href='../login'" value="Sign In"> -->
		</div>
	</div>

{% endblock %}

frontend/engine_1/templates/engine_1/tester.html
{% extends 'engine_1/base.html'}

{% block content %}
<div>
	
</div>
{% endblock %}

frontend/engine_1/templates/engine_1/upload.html
{% extends 'engine_1/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row justify-content-center">
	<div class="col-8">
		<h1>Upload</h1>
		<form action="" method="POST" accept-charset="utf-8">
			{% csrf_token %}
			{{ form|crispy }}
			{% if error %}
				<p class="text-danger">{{ error }}</p>
			{% endif %}
			<div class="d-flex justify-content-between">
				<a href="{% url 'engine_1:home' %}" title="" class="btn btn-secondary">Back</a>
				<input type="submit" value="Upload" class="btn btn-success">
			</div>
		</form>
		
	</div>
</div>
{% endblock %}

frontend/engine_1/templates/engine_1/upload_index.html
{% extends 'engine_1/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="d-flex">
	<div class="w-50">
		<h1>Upload Info</h1>
		<form method="POST" class="w-75">
			{% csrf_token %}
			{{ form|crispy }}
			<div>
				<a href="{% url 'engine_1:home' %}" title="" class="btn btn-secondary">Back</a>
				<a href="" class="btn btn-info">Test</a>
				<input type="submit" value="Update" class="btn btn-success">
			</div>
		</form>
	</div>
	<div class="w-50">
		<h1>History</h1>
		<div class="text-right">
			<h2>RunTime</h2>
		</div>
		<div class="text-right">
			<h2>Memory</h2>
		</div>
	</div>
</div>
{% endblock %}